language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+$/"
services: mysql
php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=5.0 WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=0
  global:
  - SVN_REPO: https://plugins.svn.wordpress.org/gianism/
  - secure: "SoQvImLE6BURpTxCgnN05XQAhCPGARVDxvqmz9W+WEbzy/dQYSP2mFMDwspeCk7WcNjDzzCjDk6Zz3SRj31rvzaYsdPOboLPkSX/n+RwiCQYWpAiiAL+OYm7RYoj+6N7cK2dzaDhYRG2sbdZ0nkS/+4J4TmEp9CtiA5Q+S5RLJo="
before_script:
- composer install
- curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.0/nvm.sh
- source $HOME/.nvm/nvm.sh
- nvm install v10.13.0
- node --version
- npm install && npm run package
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
before_deploy:
  - export WP_PULUGIN_DEPLOY=1
deploy:
  - provider: script
    script: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | sed 's/svn co -q/svn co/' | bash
    on:
      php: 5.6
      tags: true
      condition: $WP_VERSION = latest
    skip_cleanup: true
